[build]
builder = "nixpacks"
buildCommand = "cd part3/phonebook && npm ci"

[deploy]
startCommand = "cd part3/phonebook && node index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.healthcheckPath]
path = "/api/persons"